backend_project_product_backlog:
    path:     /
    defaults: { _controller: "BackendBundle:Item:productBacklog" }
    methods:  [GET, POST]

backend_project_product_backlog_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Item:new" }
    methods:  [GET, POST]
    
backend_project_product_backlog_edit:
    path:     /{itemId}/edit
    defaults: { _controller: "BackendBundle:Item:edit" }
    methods:  [GET, POST]
    
backend_project_product_backlog_delete:
    path:     /delete
    defaults: { _controller: "BackendBundle:Item:delete" }
    methods:  [POST]
    
backend_project_product_backlog_upload_attachment:
    path:     /{itemId}/uploadAttachment
    defaults: { _controller: "BackendBundle:Item:uploadAttachment" }
    methods:  [POST]
    
backend_project_product_backlog_delete_attachment:
    path:     /deleteAttachment
    defaults: { _controller: "BackendBundle:Item:deleteAttachment" }
    methods:  [POST]
    
backend_project_product_backlog_new_related_item:
    path:     /{itemId}/newRelatedItem
    defaults: { _controller: "BackendBundle:Item:newRelatedItem" }
    methods:  [GET, POST]
    
backend_project_product_backlog_change_priority:
    path:     /changePriority
    defaults: { _controller: "BackendBundle:Item:changePriority" }
    methods:  [POST]