backend_project_team:
    path:     /
    defaults: { _controller: "BackendBundle:ProjectTeam:index" }
    methods:  GET

backend_project_team_add:
    path:     /add
    defaults: { _controller: "BackendBundle:ProjectTeam:add" }
    methods:  [GET, POST]
    
backend_project_team_view:
    path:     /{userId}/view
    defaults: { _controller: "BackendBundle:ProjectTeam:view" }
    methods:  [GET]
    
backend_project_team_delete_user:
    path:     /deleteUser
    defaults: { _controller: "BackendBundle:ProjectTeam:deleteUserProject" }
    methods:  [GET, POST]
    
backend_project_team_user_edit_role:
    path:     /editRole
    defaults: { _controller: "BackendBundle:ProjectTeam:editUserRole" }
    methods:  [POST]