backend_projects_roles:
    path:     /
    defaults: { _controller: "BackendBundle:UserRole:index" }
    methods:  GET
    
backend_projects_roles_new:
    path:     /new
    defaults: { _controller: "BackendBundle:UserRole:new" }
    methods:  [GET, POST]
    
backend_projects_roles_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:UserRole:edit" }
    methods:  [GET, POST]
