backend_settings:
    path:     /
    defaults: { _controller: BackendBundle:Settings:index }
    
backend_settings_edit:
    path:     /editGeneralSettings
    defaults: { _controller: BackendBundle:Settings:edit }

backend_settings_update:
    path:     /updateGeneralSettings
    defaults: { _controller: BackendBundle:Settings:update }
    methods: [POST]
    
backend_settings_user_role:
        resource: "@BackendBundle/Resources/config/routing/settingsUserRole.yml"
        prefix:   /userRoles
