frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:    /{_locale}/private

backend_redirect:
    path: /private/login
    defaults:
        _controller: BackendBundle:Default:redirect
        route: backend_homepage
        permanent: true

