frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

frontend_redirect:
    path: /
    defaults:
        _controller: FrontendBundle:Default:redirect
        route: frontend_homepage
        permanent: true

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:    /{_locale}/private

backend_redirect:
    path: /private/login
    defaults:
        _controller: BackendBundle:Default:redirect
        route: backend_homepage
        permanent: true
        
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


