# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
            
    providers:
        backend:
            entity: { class: BackendBundle\Entity\User, property: email }

    encoders:
        backend:
            class: BackendBundle\Entity\User
            algorithm: bcrypt
            cost: 12

    firewalls:
        backend:
            pattern:    '^/[a-z]{2,3}?/private/*'
            form_login:
                check_path: backend_login_check
                login_path: backend_login
                default_target_path: backend_homepage
                always_use_default_target_path: true
            logout:
                path:   backend_logout
                target: backend_login
            anonymous: ~
            provider: backend
            

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
            
    access_control:
        - { path: '^/[a-z]{2,3}?/private/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2,3}?/private/*', roles: ROLE_USER_ACTIVE }

