frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Default:index }

frontend_features:
    path:     /features
    defaults: { _controller: FrontendBundle:Default:features }

frontend_why_agile_scrum:
    path:     /whyAgileScrum
    defaults: { _controller: FrontendBundle:Default:whyAgileScrum }

frontend_create_account:
    path:     /createAccount
    defaults: { _controller: FrontendBundle:Default:createAccount }
    methods: [GET, POST]