backend_homepage:
    path:     /
    defaults: { _controller: BackendBundle:Default:index }
    
backend_login:
    path:     /login
    defaults: { _controller: BackendBundle:Security:login }
    
backend_login_check:
    path:   /login_check
    defaults: { _controller: BackendBundle:Security:loginCheck }

backend_logout:
    path: /logout
    
backend_design_example:
    resource: "@BackendBundle/Resources/config/routing/designExample.yml"
    prefix:   /designExample
    
backend_users:
    resource: "@BackendBundle/Resources/config/routing/user.yml"
    prefix:   /users
    
backend_projects:
        resource: "@BackendBundle/Resources/config/routing/project.yml"
        prefix:   /projects
        
backend_settings:
        resource: "@BackendBundle/Resources/config/routing/setting.yml"
        prefix:   /settings
        
backend_notifications:
        resource: "@BackendBundle/Resources/config/routing/notification.yml"
        prefix:   /notifications
