services:
    indexer:
        class: BackendBundle\EventListener\Indexer
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    
    app_settings:
        class: BackendBundle\Services\AppSettings
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            tokenStorage: "@security.token_storage"
    
#    email_manager:
#        class: BackendBundle\Services\EmailManager
#        arguments: [@request_stack, @service_container, @doctrine.orm.entity_manager]

    email_manager:
        class: BackendBundle\Services\EmailManager
        arguments: 
            requestStack:   "@request_stack"
            container:      "@service_container"
            entityManager:  "@doctrine.orm.entity_manager"
    
    #servicio para pasarle el container a los formualrios (traduccion)
    backend.form.type.user.profile:
        class: BackendBundle\Form\UserProfileType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type }
     
    #servicio para los settings de la aplicacion
    backend.form.type.setting:
        class: BackendBundle\Form\SettingType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type }
    
    #servicio para formulario de proyectos de la aplicacion
    backend.form.type.project:
        class: BackendBundle\Form\ProjectType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type }
            
    #servicio para formulario de roles de usuario de la aplicacion
    backend.form.type.user.role:
        class: BackendBundle\Form\RoleType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type }

    #servicio para formulario de invitaciones a proyectos
    backend.form.type.project.proyect_invitation:
        class: BackendBundle\Form\ProjectInvitationType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type }
            
    #servicio para formulario de roles de usuario en un proyecto
    backend.form.type.user_role:
        class: BackendBundle\Form\EditUserRoleType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type }