services:
    indexer:
        class: BackendBundle\EventListener\Indexer
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    
    #servicio para pasarle el container a los formualrios (traduccion)
    backend.form.type.user.profile:
        class: BackendBundle\Form\UserProfileType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type }
